@startuml class_diagram
skinparam classAttributeIconSize 0
skinparam groupInheritance 4

class GeometricShape {
  + calcular_area()
  + calcular_perimetro()
  + distancia_origem()
  + distancia_pontos(ponto)
  + contem_ponto(ponto)
  + mover(novo_ponto)
  + __str__()
  + to_dict()
  + from_dict()
}
class Point {
  - x
  - y
  + get_x()
  + get_y()
  + distancia_origem()
  + distancia_pontos(ponto)
  + contem_ponto(ponto)
  + mover(novo_ponto)
  + __str__()
  + to_dict()
  + from_dict()
  + criar_ponto()
}
class LineSegment {
  - ponto1
  - ponto2
  + get_ponto1()
  + get_ponto2()
  + calcular_comprimento()
  + distancia_origem()
  + distancia_pontos(ponto)
  + contem_ponto(ponto)
  + mover(novo_ponto1, novo_ponto2)
  + __str__()
  + to_dict()
  + from_dict()
  + criar_segmento_de_reta()
}
class Circle {
  - centro
  - raio
  + get_centro()
  + get_raio()
  + calcular_area()
  + calcular_perimetro()
  + distancia_origem()
  + distancia_pontos(ponto)
  + contem_ponto(ponto)
  + mover(novo_ponto)
  + __str__()
  + to_dict()
  + from_dict()
  + criar_circulo()
}
class Rectangle {
  - centro
  - largura
  - altura
  + get_centro()
  + get_largura()
  + get_altura()
  + calcular_area()
  + calcular_perimetro()
  + distancia_origem()
  + distancia_pontos(ponto)
  + contem_ponto(ponto)
  + mover(novo_ponto)
  + __str__()
  + to_dict()
  + from_dict()
  + criar_retangulo()
}
class Triangle {
  - ponto1
  - ponto2
  - ponto3
  + get_ponto1()
  + get_ponto2()
  + get_ponto3()
  + calcular_centro()
  + calcular_area()
  + calcular_perimetro()
  + distancia_origem()
  + distancia_pontos(ponto)
  + contem_ponto(ponto)
  + mover(novo_ponto)
  + __str__()
  + to_dict()
  + from_dict()
  + formar_triangulo(ponto1, ponto2, ponto3)
  + criar_triangulo()
}

interface IRepository {
  + add(item)
  + list_all()
  + get(index)
  + remove(index)
}

class InMemoryRepository {
  - items[]
  + add(item)
  + list_all()
  + get(index)
  + remove(index)
}

class CreateShape {
  - repository
  - factory
  + execute(tipo_forma)
}
class MoveShape {
  - repository
  + execute(index, novo_ponto1, novo_ponto2 = None)
}
class CalculateMetrics {
  - repository
  + calcular_area(index)
  + calcular_perimetro(index)
  + distancia_origem(index)
  + distancia_pontos(index, ponto)
  + contem_ponto(index, ponto)
}

class ShapeFactory {
  + criar_forma(tipo_forma)
}

class GeometricShapeController {
  - factory
  - repository
  - create_shape_use_case
  - move_shape_use_case
  - calculate_metrics_use_case
  + adicionar_forma_geometrica(tipo_forma)
  + listar_formas_geometricas()
  + calcular_area(index)
  + calcular_perimetro(index)
  + distancia_origem(index)
  + distancia_pontos(index, ponto)
  + contem_ponto(index, ponto)
  + mover_forma(index, novo_ponto)
  + mover_segmento_de_reta(index, novo_ponto1, novo_ponto2)
  + remover_forma_geometrica(index)
  + adicionar_ponto()
  + adicionar_segmento_de_reta()
  + adicionar_circulo()
  + adicionar_retangulo()
  + adicionar_triangulo()
}

class GeometricShapeView {
  + mostrar_menu()
  + mostrar_menu_formas()
  + mostrar_menu_metodos()
  + mostrar_mover()
  + mostrar_menu_repositorios()
  + ler_opcao()
  + limpar_tela()
  + obter_indice_forma_geometrica()
  + mostrar_resultado(resultado, mensagem)
  + mostrar_menu_remover_forma()
}

class GeometricShapeApp {
  - controller
  - view
  + selecionar_repositorio(file_path)
  + run()
  - handle_adicionar_forma()
  - adicionar_forma(func_adicionar)
  - handle_metodos_forma()
  - calcular_e_mostrar(func_calcular, label)
  - calcular_e_mostrar_distancia_pontos()
  - calcular_e_mostrar_contem_ponto()
  - mover_forma()
  - mover_segmento_de_reta(index)
  - mover_formas(index)
  - handle_remover_forma()
  - listar_formas(formas)
}

@enduml
